Update Fish-Blog-Deploy.yml

diff --git a/.github/workflows/Fish-Blog-Deploy.yml b/.github/workflows/Fish-Blog-Deploy.yml
--- a/.github/workflows/Fish-Blog-Deploy.yml
+++ b/.github/workflows/Fish-Blog-Deploy.yml
@@ -39,13 +39,10 @@ jobs:
       with:
         node-version: 16
         
-    - name: Setup NPM Env
+    - name: Reset container permissions
       run: |
-        npm ci
-        echo "Configure npm global path now ..."
-        mkdir -p ~/.npm-global
-        npm config set prefix ~/.npm-global
-        echo "PATH=$HOME/.npm-global/bin:$PATH" >> $GITHUB_PATH
+        sudo chown -R runner:docker ~/
+        sudo chmod -R 755 ~/.npm
 
     - name: Setup Hexo Env
       run: |
@@ -54,7 +51,9 @@ jobs:
 
     - name: Verify Versions
       run: |
-        echo "node version:$(node -v) , npm version:$(npm -v)"
+        echo "Node version: $(node -v)"
+         echo "NPM version: $(npm -v)"
+        echo "Hexo path: $(which hexo || echo 'not found')"
 
     - name: Download YorkFish-Blog-Source to source/_posts
       run: |
